<?php
/**
 * @file
 * Mobile Codes core functions.
 */

/**
 * Include additional files.
 */
foreach (module_list() as $module) {
  if (file_exists($file = dirname(__FILE__) . "/includes/{$module}.inc")) {
    require_once $file;
  }
}

/**
 * Implements hook_init().
 */
function mobile_codes_init() {
  if (!module_exists('ctools')) {
    module_enable(array('ctools'));
    if (!module_exists('ctools')) {
      drupal_set_message(t('Mobile Codes has been disabled as the required !ctools module is not present.', array('!ctools' => l(t('Chaos tool suite'), 'http://drupal.org/project/ctools'))), 'error');
      module_disable(array('mobile_codes'));
    }
  }
}

/**
 * Implements hook_perm().
 */
function mobile_codes_perm() {
  return array('administer mobile codes');
}

/**
 * Implements hook_mobile_codes_menu_alter().
 */
function mobile_codes_mobile_codes_menu_alter($items) {
  $items['admin/settings/mobile_codes/settings'] = array(
    'title' => 'Settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('mobile_codes_settings_form'),
    'access arguments' => array('administer mobile codes'),
    'file' => 'includes/mobile_codes.admin.inc',
    'type' => MENU_LOCAL_TASK,
    'weight' => 10,
  );

  $items['ahah/mobile_codes'] = array(
    'title' => 'Mobile Codes AHAH callback',
    'page callback' => 'mobile_codes_ahah',
    'page arguments' => array(2, 3),
    'access arguments' => array('administer mobile codes providers'),
    'type' => MENU_CALLBACK,
  );
}

/**
 * Implements hook_menu_alter().
 */
function mobile_codes_menu_alter(&$items) {
  // @TODO - Make this better.
  if (isset($items['admin/settings/mobile_codes/presets'])) {
    $items['admin/settings/mobile_codes'] = array_merge(
      $items['admin/settings/mobile_codes/presets'],
      array(
        'title' => 'Mobile Codes',
        'type' => MENU_NORMAL_ITEM,
      )
    );
    $items['admin/settings/mobile_codes/presets']['type'] = MENU_DEFAULT_LOCAL_TASK;
    $items['admin/settings/mobile_codes/presets']['parent'] = 'admin/settings/mobile_codes';
    $items['admin/settings/mobile_codes/providers']['type'] = MENU_LOCAL_TASK;
    $items['admin/settings/mobile_codes/providers']['parent'] = 'admin/settings/mobile_codes';
  }
}

/**
 * Implements hook_mobile_codes_theme_alter().
 */
function mobile_codes_mobile_codes_theme_alter($items) {
  $items['mobilecode'] = array(
    'arguments' => array(
      'text' => NULL,
      'data' => array(),
    ),
  );
}

/**
 * Generate a mobile code.
 */
function mobile_codes_generate($url) {
  if (!file_exists($file = file_directory_path() . '/mobile_codes/' . md5(serialize($url)) . '.png')) {
    $request = drupal_http_request($url);
    if ($request->code == 200) {
      if (file_check_directory($dir = file_directory_path() . '/mobile_codes', FILE_CREATE_DIRECTORY)) {
        file_save_data($request->data, $file);
      }
    }

    else {
      return FALSE;
    }
  }
  return $file;
}

/**
 *
 */
function mobile_code_data_type($text) {
  switch ($text) {
    case valid_url($text, TRUE):
      return 'url';

    default:
      return 'text';
  }
}

/**
 *
 */
function mobile_codes_process_url($text, $data) {
  if (isset($data['#preset']) || isset($data['#provider'])) {
    ctools_include('export');
    if (isset($data['#preset'])) {
      $preset = clone(ctools_export_crud_load('mobile_codes_presets', $data['#preset']));
      $data['#provider'] = $preset->provider;
      $data = array_merge($data, $preset->defaults);
    }

    $provider = clone(ctools_export_crud_load('mobile_codes_providers', $data['#provider']));
    foreach (element_children($provider->parameters) as $parameter) {
      if (!isset($data[$parameter])) {
        switch ($provider->parameters[$parameter]['type']) {
          case 'data':
            mobile_codes_process_text($text);
            $data[$parameter] = urlencode($text);
            break;

          case 'select':
            $provider->parameters[$parameter]['value'] = explode("\n", $provider->parameters[$parameter]['value']);
            $provider->parameters[$parameter]['value'][0] = explode("|", $provider->parameters[$parameter]['value'][0]);
            $data[$parameter] = $provider->parameters[$parameter]['value'][0][0];
            break;

          case 'text':
            drupal_set_message(t('Mobile Codes argument %arg missing.', array('%arg' => $parameter)), 'error');
            return '';
        }
      }
      $provider->url = str_replace("[{$parameter}]", $data[$parameter], $provider->url);
    }
    dpm($provider->url);
    return $provider->url;
  }
  return FALSE;
}

/**
 *
 */
function mobile_codes_process_text(&$text) {
  $settings = array();
  $type = mobile_code_data_type($text);
  $defaults = variable_get('mobile_codes_settings', array(
    'url' => array(
      'alias' => 'alias',
    ),
  ));

  drupal_alter('mobile_codes_settings', $settings);
  if (is_array($settings[$type]) && count($settings[$type]) > 0) {
    foreach ($settings[$type = mobile_code_data_type($text)] as $setting => $values) {
      if ($defaults['url'][$setting]) {
        $weight = isset($values['weight']) ? $values['weight'] : 0;
        $order[$weight] = is_array($order[$weight]) ? $order[$weight] : array();
        $order[$weight][] = $setting;
      }
    }

    ksort($order);
    foreach ($order as $settings) {
      sort($settings);
      foreach ($settings as $setting) {
        if (function_exists($function = "mobile_codes_data_{$type}_{$setting}")) {
          $function(&$text);
        }
      }
    }
  }
}


/**
 *
 */
function mobile_codes_ahah($section, $op = NULL) {
  // Immediately disable devel shutdown functions so that it doesn't botch our
  // JSON output.
  $GLOBALS['devel_shutdown'] = FALSE;

  if (empty($_POST['form_build_id'])) {
    // Invalid request.
    drupal_set_message(t('An unrecoverable error occurred.'));
    print drupal_to_js(array('data' => theme('status_messages')));
    exit;
  }

  // Load the form.
  $form_state = array(
    'rebuild' => TRUE,
    'storage' => NULL,
    'submitted' => FALSE
  );
  $form_build_id = $_POST['form_build_id'];
  $form = form_get_cache($form_build_id, $form_state);
  $args = $form['#parameters'];
  $form_id = array_shift($args);
  $form_state['post'] = $form['#post'] = $_POST;
  $form['#programmed'] = $form['#redirect'] = FALSE;
  form_set_error(NULL, '', TRUE);

  // Process the form with drupal_process_form(), which calls the submit
  // handlers that puts whatever was worthy of keeping in the $form_state.
  drupal_process_form($form_id, $form, $form_state);

  // Session messages would get displayed at the next regular request, but
  // we're in AHAH here, so that won't happen. Make them go away.
  unset($_SESSION['messages']);
  form_set_error(NULL, '', TRUE);

  if (function_exists($function = "mobile_codes_ahah_{$section}_{$op}") || function_exists($function = "mobile_codes_ahah_{$section}")) {
    $output = $function($form_id, $form, $form_state, $args, $form_build_id);
  }

  print drupal_to_js(array('status' => TRUE, 'data' => $output));
}

/**
 * Theme function for displaying Mobile Codes
 */
function theme_mobilecode($text, $data) {
  if ($url = mobile_codes_process_url($text, $data)) {
    if ($file = mobile_codes_generate($url)) {
      return theme('image', $file);
    }
  }
  // @TODO - Set error.
  return 'Error';
}
